# InfluxDB Einstellungen
influxdb:
  url: "http://localhost:8086"
  token: "your_influxdb_token"
  org: "your_organization"
  bucket: "your_bucket"
  visualization_query_range: "7d"  # Zeitraum für Visualisierungen
  training_query_range: "all"      # Zeitraum für Trainingsdaten

# MQTT Einstellungen
mqtt:
  broker: "mqtt.example.com"
  port: 8883                    # Standardport für MQTT über SSL, 1883 für unverschlüsselt
  username: "mqtt_user"
  password: "mqtt_password"
  use_ssl: true                  # Aktiviert SSL/TLS, falls auf true gesetzt
  ca_cert: "/path/to/ca.crt"     # Pfad zur CA-Zertifikatsdatei (nur erforderlich, wenn use_ssl: true)

# Allgemeine Einstellungen
general:
  interval: 60                   # Intervall (in Sekunden) für das Abrufen und Senden von Daten

# Vorhersage und Wetterdaten Einstellungen
prediction:
  include_weather: true           # Aktiviert die Einbindung von Wetterdaten
  weather:
    api_key: "your_openweather_api_key"
    location: "Zorneding,DE"      # Standort für die Wettervorhersage
    update_interval: 3600         # Intervall (in Sekunden) für das Abrufen der Wetterdaten
    error_handling: true          # Aktiviert erweitertes Fehlerhandling bei der Wetterdatenabfrage

# API Einstellungen für das Web-Dashboard
api:
  enabled: true                   # Aktiviert das Web-Dashboard (Flask-App)
  port: 5000                      # Port, auf dem das Web-Dashboard läuft
