modbus:
  host: "192.168.1.100"
  port: 502
  unit_id: 1  # Configurable unit ID for Modbus

mqtt:
  broker: "mqtt.example.com"
  port: 1883
  topic: "solaredge"
  use_ssl: true
  ca_cert: "/path/to/ca_cert.pem"

influxdb:
  host: "localhost"
  database: "energy_data"

weather:
  enabled: true
  api_key: "your_openweathermap_api_key"

general:
  interval: 10                 # Interval in seconds for data retrieval
  reconnect_attempts: 3        # Number of reconnection attempts
  reconnect_delay: 5           # Delay in seconds between retries

training:
  enabled: true
  interval: 86400              # Training every day
  learning_rate: 0.
