# InfluxDB settings
influxdb:
  url: "http://localhost:8086"
  token: "your-influxdb-token"
  org: "your-org-name"
  bucket: "solar_edge_data"
  visualization_query_range: "7d"
  training_query_range: "all"

# MQTT configuration
mqtt:
  broker: "192.168.1.101"
  port: 1883
  topic: "solaredge"
  username: "mqtt_user"
  password: "mqtt_password"
  backup_broker: "192.168.1.102"

# General settings
general:
  interval: 60
  reconnect_attempts: 5
  reconnect_delay: 10

# Prediction settings
prediction:
  enabled: true
  forecast_interval: 60
  include_weather: true           # Aktiviert die Wetterintegration
  weather:
    api_key: "your-weather-api-key"
    location: "Zorneding,85604"   # Standort für die Wettervorhersage
    provider: "openweather"       # Wetteranbieter (z.B., "openweather")
    update_interval: 3600         # Aktualisierungsintervall für Wetterdaten (in Sekunden)

# API settings for web interface
api:
  enabled: true
  port: 5000

# Optional features
features:
  anomaly_detection: true
  anomaly_threshold: 10
  aggregation: true
  backup_mqtt: true
  compression: true
