modbus:
  host: "192.168.1.100"
  port: 502
  unit_id: 1                  # Configurable unit ID for Modbus

mqtt:
  broker: "mqtt.example.com"
  port: 1883
  use_ssl: true
  ca_cert: "/path/to/ca_cert.pem"
  topic: "solaredge"           # Base topic for MQTT publishing

influxdb:
  host: "localhost"
  database: "energy_data"

weather:
  enabled: true                # Enable/disable weather retrieval
  api_key: "your_openweathermap_api_key"
  location: "Zorneding,DE"
  cache_path: "weather_cache.json"

training:
  enabled: true
  interval: 86400              # Training interval in seconds (default: daily)
  learning_rate: 0.01          # Model learning rate
  model_path: "energy_model.pkl"
  drift_threshold: 100         # Threshold for retraining due to drift

notifications:
  enabled: true
  email_sender: "your_email@example.com"
  email_recipient: "recipient_email@example.com"
  smtp_server: "smtp.example.com"
  email_password: "your_email_password"

general:
  interval: 10                 # Main loop interval in seconds
  reconnect_attempts: 3        # Number of reconnection attempts
  reconnect_delay: 5           # Delay in seconds between retries
