# Modbus configuration
modbus:
  host: "192.168.1.100"         # IP-Adresse des SolarEdge Geräts
  port: 502                      # Standard-Port für Modbus TCP
  unit_id: 1                     # Modbus Unit ID des SolarEdge Geräts

# MQTT configuration
mqtt:
  broker: "192.168.1.101"        # IP-Adresse des MQTT Brokers
  port: 1883                     # Standard-Port für MQTT
  topic: "solaredge"             # Basis-Topic für MQTT-Nachrichten
  username: "mqtt_user"          # Optionaler MQTT-Benutzername
  password: "mqtt_password"      # Optionales MQTT-Passwort

# General settings
general:
  interval: 60                   # Intervall in Sekunden für Datenabrufe
  reconnect_attempts: 5          # Anzahl der Wiederholungsversuche bei Verbindungsproblemen
  reconnect_delay: 10            # Verzögerung in Sekunden zwischen Wiederholungsversuchen

# Optional API settings
api:
  enabled: true                  # Aktiviert die API zur Laufzeit-Datenanzeige
  port: 5000                     # Port für die API (nur wenn enabled: true)
